# In this notebook, we're going to cover some of the most fundamental concepts of tensors using Tensor

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Exercises to try for yourself!

## Introduction to Tensors

In [188]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [189]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [190]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [191]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [192]:
# Check the dimension of our vector
vector.ndim

1

In [193]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [194]:
# Check the dimension of our matrix
matrix.ndim

2

In [195]:
# Create another matrix
another_matrix = tf.constant([[10.,7],
                             [3.,2],
                             [8,9]], dtype=tf.float16) # specify the data type dtype

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [196]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [197]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [198]:
tensor.ndim

3

What we6've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

## Creatin tensors with tf.Variable

In [199]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [200]:
changeable_tensor == unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True,  True])>

In [201]:
# Let's try change one of the elements in our changeable tensor
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [202]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [203]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

&#x1F511; **Note:** Rarely in practice you will need to decide whether to use 'tf.constant' or 'tf.Variable' to create tensors, as TensorFlow does this for you. However, if in doubt, use 'tf.constant' and change it later if needed.

### Creating random tensors

Random tensors are tensors of arbitrary size which contain random numbers

In [204]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [205]:
# Are they equal?
random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [206]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent)
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]])>

In [207]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [208]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

&#x1F6E0;**Exercise:** Read through TensorFlow documentation on random seed generation:
https://www.tensorflow.org/api_docs/pythontf/random/set_seed and practice writing 5 random tensors and shuffle them.

It looks like if we want our shuffled tensors to be in the same order, we6've got to use the global level and operation level random seed:

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjuction to determine the random sequence.

In [209]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### Other ways to make Tensors

In [210]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [211]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### You can also turn NumPy arrays in tensors

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU for faster computing).

In [212]:
# You can also turn Numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32) # create a NumPy array between 1 and 25
numpy_A

# X = tf.constant (some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [213]:
A = tf.constant(numpy_A, shape=(2,3,4))
B =tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### Getting information from tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape  
* Rank  
* Axis 
* Size

In [214]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [215]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [216]:
# Get various attributes of our tensor
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1] )
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists

In [217]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [218]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[0,0,0]
rank_4_tensor[:1,:1,:1] # Use this

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [219]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7,5],
                             [8,5,8],
                            [7,10,9]])
rank_2_tensor

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  5],
       [ 8,  5,  8],
       [ 7, 10,  9]])>

In [220]:
rank_2_tensor.ndim

2

In [221]:
# Get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 8, 9])>

In [222]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[10],
        [ 7],
        [ 5]],

       [[ 8],
        [ 5],
        [ 8]],

       [[ 7],
        [10],
        [ 9]]])>

In [223]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # expand the last axis

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[10],
        [ 7],
        [ 5]],

       [[ 8],
        [ 5],
        [ 8]],

       [[ 7],
        [10],
        [ 9]]])>

In [224]:
# Expand the 0- axis
tf.expand_dims(rank_2_tensor,0)

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[10,  7,  5],
        [ 8,  5,  8],
        [ 7, 10,  9]]])>

### Manipulating tensors (tensor operations)

**Basic operations**

`+`,`-`,`*`,`/`

In [225]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [226]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [227]:
# Subtration also works
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [228]:
# We can use the tensorflow built-in functions also
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

### Matrix Multiplication

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfill if we6're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [229]:
# Matrix multiplication in tensorflow
print(tensor,'\n\n\n')
tf.matmul(tensor,tensor)


tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32) 





<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [230]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [231]:
# Create a tensor (3,2) tensor
x = np.random.randint(1,high=10,size=6)
X = tf.constant(x,shape=(3,2))

# Create another tensor (2,3) tensor
y = np.random.randint(1,10,6)
Y = tf.constant(y,shape=(2,3))


In [232]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[7, 3],
        [5, 9],
        [6, 1]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 4, 2],
        [4, 7, 3]])>)

In [233]:
# Try to matrix multiply tensors
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[40, 49, 23],
       [56, 83, 37],
       [28, 31, 15]])>

&#x1F4D6; **Resource:** Info and example of matrix multiplication: https://mathsisfun.com/algebra/matrix-multiplying.html

In [234]:
# Try to matrix multiply tensors of same shape
tensor_1 = tf.constant([[10,3],
                       [7,2],
                       [5,4]])
tensor_2 = tf.constant([[3,4],
                       [6,5],
                       [2,1]])

In [235]:
tensor_1 @ tensor_2

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [236]:
# Use tf.reshape to reshape you tensor
tf.reshape(tensor_2,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 6],
       [5, 2, 1]])>

In [237]:
# Try to matrix multiply X by reshaped Y
tensor_1 @ tf.reshape(tensor_2,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[45, 46, 63],
       [31, 32, 44],
       [35, 28, 34]])>

In [238]:
tf.matmul(tensor_1, tf.reshape(tensor_2,shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[45, 46, 63],
       [31, 32, 44],
       [35, 28, 34]])>

In [239]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[7, 3],
        [5, 9],
        [6, 1]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[7, 5, 6],
        [3, 9, 1]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[7, 3, 5],
        [9, 6, 1]])>)

In [240]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tensor_1,tf.transpose(tensor_2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[42, 75, 23],
       [29, 52, 16],
       [31, 50, 14]])>

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`
* `@`


In [241]:
tensor_1, tensor_2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  3],
        [ 7,  2],
        [ 5,  4]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [6, 5],
        [2, 1]])>)

In [242]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

tf.tensordot(tf.transpose(tensor_1),tensor_2,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[82, 80],
       [29, 26]])>

In [243]:
# Perform matrix multiplication between X and Y(transposed)
tf.matmul(tensor_1,tf.transpose(tensor_2))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[42, 75, 23],
       [29, 52, 16],
       [31, 50, 14]])>

In [244]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(tensor_1,tf.reshape(tensor_2,shape=[2,3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[45, 46, 63],
       [31, 32, 44],
       [35, 28, 34]])>

In [245]:
# Check the values of tensor_1, reshape tensor_1, transposed tensor_1
print("Normal tensor_1")
print(tensor_1,"\n") # "\n" is for newline
print("tensor_1 reshaped to (2,3):")
print(tf.reshape(tensor_1,(2,3)), "\n")
print("tensor_1 transposed:")
print(tf.transpose(tensor_1))

Normal tensor_1
tf.Tensor(
[[10  3]
 [ 7  2]
 [ 5  4]], shape=(3, 2), dtype=int32) 

tensor_1 reshaped to (2,3):
tf.Tensor(
[[10  3  7]
 [ 2  5  4]], shape=(2, 3), dtype=int32) 

tensor_1 transposed:
tf.Tensor(
[[10  7  5]
 [ 3  2  4]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) to satisfy the matrix multiplication rule

### Changing the datatype of a tensor

In [246]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [247]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [248]:
# Change from float32 to float16 (reduced precision)
D= tf.cast(B,dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [249]:
# Change from int32 to float32
E = tf.cast(C,dtype=tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [250]:
E_float16 = tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of value

In [251]:
# Get the absolute values
D = tf.constant([-7,10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Lets go through the following form of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [252]:
# minimum
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [253]:
# maximum
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [254]:
# mean
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [255]:
# sum
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [256]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([39, 95, 63, 76, 68, 81, 18,  4, 49, 88, 89, 44, 39,  4, 28, 70, 36,
       53, 64, 12, 79, 81, 92, 38, 55, 36, 52, 59, 75, 42, 48, 42, 16, 96,
       37, 73, 12, 65, 44, 18,  3, 90, 14, 75, 95, 27, 88, 33, 80, 80])>

In [257]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [258]:
# minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [259]:
# maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=96>

In [260]:
# mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=53>

In [261]:
# sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2665>

&#x1F6E0;**Exercise:** With what've just learned, find the variance and standard deviation of our `E` tensor using Tensorflow methods.

In [262]:
# To find the standard deviation, we need to use tf.math.reduce_std

tf.math.reduce_std(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.61>

In [263]:
# To find the variance we use tf.math.reduce_variance

tf.math.reduce_variance(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=762.0>

### Find the positional maximum and minimum

In [264]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [265]:
# Get the position of the maximum element
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [266]:
# Get the position of the minimum element
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [267]:
# Check for equality
tf.reduce_max(F)==F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [268]:
# Find the minimum values
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimension)

In [269]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = [1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [270]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [271]:
G_squeezed= tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encodingg tensors

In [272]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [273]:
# Specify custom values for one hot encoding

tf.one_hot(some_list,depth=4, on_value=True, off_value=False)

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>

### Squaring, log, square root

In [274]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [275]:
# Find the Square tensor
tf.square(H).numpy()

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [276]:
# Find the Square root
tf.sqrt(tf.cast(H,dtype=tf.float16)).numpy()

array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)

In [277]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float16)).numpy()

array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

&#x1F5DD; **Note:** One of the main differences between a TensorFlow tensor and a Numpy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing).

In [278]:
#  Create a tensor directly from a NumPy array
J = tf.constant(np.array([3,7,10]))
J

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  7, 10])>

In [279]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3,  7, 10]), numpy.ndarray)

In [280]:
# Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3,  7, 10]), numpy.ndarray)

In [281]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5,5,8]))
tensor_J = tf.constant([3.,5,5,8])

# Check the datatypes of each 
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [282]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [283]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


&#x1F511; **Note:** If youi have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.